name: hybridds
dependencies:
  - dataclasses=0.8
  - dill=0.3.4
  - gflags=2.2.2
  - glog=0.5.0
  - huggingface_hub=0.29.2
  - multiprocess=0.70.12.2
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.16
  - pip=25.1
  - pyarrow=19.0.0
  - requests=2.32.3
  - setuptools=78.1.1
  - urllib3=1.26.19
  - pip:
      - datasets==3.6.0
      - accelerate==1.9.0
      - anthropic==0.58.2
      - blobfile==3.0.0
      - cachetools==5.5.2
      - certifi==2025.4.26
      - compressed-tensors==0.9.4
      - fake-useragent==2.2.0
      - fastapi-cli==0.0.7
      - gguf==0.16.3
      - google-search-results==2.4.2
      - googleapis-common-protos==1.70.0
      - grpcio==1.71.0
      - huggingface-hub==0.32.4
      - networkx==3.4.2
      - nltk==3.9.1
      - openai==1.99.5
      - packaging==25.0
      - pandas==2.2.3
      - pdfplumber==0.11.6
      - protobuf==4.25.7
      - psutil==7.0.0
      - ray==2.46.0
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - sentence-transformers==5.0.0
      - tokenizer==3.4.5
      - torch==2.7.0
      - torchaudio==2.7.0
      - torchvision==0.22.0
      - tqdm==4.67.1
      - transformers==4.53.1
      - triton==3.3.0
      - trl==0.17.0
      - vllm==0.9.0.1
      - pip-system-certs
      - wandb
